[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Errors
anyways = "*"

# Logging
tracing = "0.1.35"
tracing-subscriber = "0.3.11"
tracing-error = "0.2.0"

# Data
serde = { version = "1.0.137", features = ["derive"] }
semver = { version = "1.0.10", features = ["serde"] }

# World
hecs = "0.7.6"
rustaria = { path = "../" }

# Lua
apollo = { path = "../libs/apollo", features = ["luajit", "vendored", "serialize", "macro"] }

# Rendering
glfw = { version = "0.45.0", features = ["image"] }
glium = { git = "https://github.com/alphaqu/glium", default-features = false, features = [] }
image = { version = "0.24.2", default-features = false, features = ["png"] }

# Networking
laminar = "0.5.0"
bincode = "1.3.3"

# Async
rayon = "1.5.3"
crossbeam = "0.8.1"
parking_lot = "0.12.0"

# Math
rectangle-pack = "0.4.2"
euclid = "0.22.7"

# Util
fxhash = "0.2.1"
bitflags = "1.3.2"
type-map = "0.5"



