[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustaria = { path = "../../" }
rustaria-util = { path = "../../libs/rustaria-util" }
rustaria-api = { path = "../../libs/rustaria-api" }
rustaria-network = { path = "../../libs/rustaria-network" }
rustaria-graphics = { path = "../../libs/rustaria-graphics" }
rustaria-controller = { path = "../../libs/rustaria-controller" }
glfw = "0.44.0"
