[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustaria = { path = "../../", features = ["client"] }
rustaria-common = { path = "../../libs/rustaria-common" }
rustaria-api = { path = "../../libs/rustaria-api" }
rustaria-network = { path = "../../libs/rustaria-network" }
rustariac-rendering = { path = "../../libs/rustariac-rendering" }
rustariac-backend = { path = "../../libs/rustariac-backend" }
rustariac-glium-backend = { path = "../../libs/rustariac-glium-backend" }
rustaria-input = { path = "../../libs/rustaria-input" }
rayon = "1.5.1"
glfw = "0.44.0"
clap = { version = "3.1.9", features = ["derive"] }
