[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raw-cpuid = "10.3.0"
rayon = "1.5.3"

rustaria = { path = "../../" }
rsa-core = { path = "../../libs/rsa-core" }
rsa-input = { path = "../../libs/rsa-input" }
rsa-network = { path = "../../libs/rsa-network" }
rsac-graphic = { path = "../../libs/rsac-graphic" }
