[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raw-cpuid = "10.3.0"


rustaria = { path = "../../" }
rsa-core = { path = "../../libs/rsa-core" }
rsa-input = { path = "../../libs/rsa-input" }
rsac-graphic = { path = "../../libs/rsac-graphic" }
