[package]
name = "rustaria"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "./apps/rsa-client",
    "./apps/rsa-server",
    "./libs/mooncake",
    "./libs/rsa-api",
    "./libs/rsa-build",
    "./libs/rsa-chunk",
    "./libs/rsa-common",
    "./libs/rsa-comps",
    "./libs/rsa-network",
    "./libs/rsa-world",
    "./libs/rsa-todo",
]