[package]
name = "rustaria"
version = "0.1.0"
authors = ["leocth <leocth31@gmail.com>", "alphaqu <yan.gyunashyan@gmail.com>"]
description = "A Terraria rework in Rust"
repository = "https://github.com/rustaria/rustaria/"
license = "GPL-3.0-or-later"
edition = "2021"
rust-version = "1.60"

[dependencies]
serde = { version = "1.0.133", features = ["derive"] }
type-map = "0.5.0"
rayon = "1.5.1"
crossbeam = "0.8.1"
mlua = { git = "https://github.com/alphaqu/mlua", branch = "alphacurseness", features = ["serialize", "send"] }

frogelua = { path = "./libs/frogelua" }
macro-module = { path = "./libs/macro-module" }
rsa-core = { path = "libs/rsa-core" }
rsa-network = { path = "libs/rsa-network" }

[workspace]
members = [
    "libs/frogelua",
    "libs/apollo",
    "libs/macro-module",
    "libs/rsa-network",
    "libs/rsa-core",
    "libs/rsa-gen",
    "libs/rsa-input",
    "libs/rsa-item",
    "libs/rsac-rendering",
    "libs/rsac-backend",
    "libs/rsac-glium-backend",
    "runtime/client",
]

[features]
client = []

[profile.release]
panic = "abort"
opt-level = 3
lto = "thin"

[profile.dev]
opt-level = 1

[profile.test]
opt-level = 1

