[package]
name = "rustaria"
version = "0.1.0"
authors = ["leocth <leocth31@gmail.com>", "alphaqu <yan.gyunashyan@gmail.com>"]
description = "A Terraria rework in Rust"
repository = "https://github.com/rustaria/rustaria/"
license = "GPL-3.0-or-later"
edition = "2021"
rust-version = "1.60"

[dependencies]
serde = { version = "1.0.133", features = ["derive"] }
type-map = "0.5.0"
legion = "0.4.0"
rayon = "1.5.1"
crossbeam = "0.8.1"
image = "*"

rustaria-util = { path = "./libs/rustaria-util" }
rustaria-api = { path = "./libs/rustaria-api" }
rustaria-network = { path = "./libs/rustaria-network" }

[build-dependencies]
zip = "0.5.0"
walkdir = "2.3.2"

[workspace]
members = [
    "libs/mooncake",
    "libs/aloy",
    "libs/rustaria-network",
    "libs/rustaria-util",
    "libs/rustaria-graphics",
    "libs/rustaria-rendering",
    "libs/rustaria-controller",
    "libs/rustaria-api",
    "runtime/client",
]

[features]
client = []

[profile.release]
panic = "abort"
opt-level = 3
lto = "thin"
