[package]
name = "rustaria"
version = "0.1.0"
authors = ["leocth <leocth31@gmail.com>", "alphaqu <leocth31@gmail.com>"]
description = "A Terraria rework in Rust"
repository = "https://github.com/rustaria/rustaria/"
license = "GPL-3.0-or-later"
edition = "2021"
rust-version = "1.57"

[dependencies]
mlua = { version = "0.7.1", features = ["luajit", "vendored", "serialize"] }
tokio = { version = "1.15.0" }
tracing = "0.1.29"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.5", features = ["env-filter", "time"] }
eyre = "0.6.5"
serde = { version = "1.0.133", features = ["derive"] }
mooncake = { path = "mooncake" }
bimap = "0.6.1"

[build-dependencies]
zip = "0.5.0"
walkdir = "2.3.2"

[workspace]
members = ["mooncake", "rustaria-client", "rustaria-server"]

[profile.release]
panic = "abort"
opt-level = 3
lto = "thin"
