[package]
name = "rustaria"
version = "0.1.0"
authors = ["leocth <leocth31@gmail.com>", "alphaqu <yan.gyunashyan@gmail.com>"]
description = "A Terraria rework in Rust"
repository = "https://github.com/rustaria/rustaria/"
license = "GPL-3.0-or-later"
edition = "2021"
rust-version = "1.60"

[dependencies]
serde = { version = "1.0.133", features = ["derive"] }
type-map = "0.5.0"
rayon = "1.5.1"
crossbeam = "0.8.1"
mlua = { git = "https://github.com/alphaqu/mlua", branch = "alphacurseness", features = ["serialize", "send"] }


frogelua = { path = "./libs/frogelua" }
rustaria-common = { path = "libs/rustaria-common" }
rustaria-api = { path = "./libs/rustaria-api" }
rustaria-network = { path = "./libs/rustaria-network" }

[workspace]
members = [
    "libs/frogelua",
    "libs/rustaria-network",
    "libs/rustaria-common",
    "libs/rustaria-gen",
    "libs/rustaria-controller",
    "libs/rustaria-api",
    "libs/rustariac-rendering",
    "libs/rustariac-backend",
    "libs/rustariac-glium-backend",
    "runtime/client",
]

[features]
client = []

[profile.release]
panic = "abort"
opt-level = 3
lto = "thin"

[profile.dev]
opt-level = 1

[profile.test]
opt-level = 1

