[package]
name = "rustaria"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
wasmer = "2.1.1"
wasmer-wasi = "2.1.1"
wgpu = { version = "0.12.0", features = ["spirv"] }
winit = "0.26.0"
futures = "0.3.19"
tokio = { version = "1.15.0", features = ["rt-multi-thread", "macros", "fs"] }
tokio-stream = { version = "0.1.8", features = ["fs"] }
tracing = "0.1.29"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.5", features = ["env-filter", "time"] }
time = { version = "0.3.5", features = ["macros"] }
eyre = "0.6.5"
color-eyre = "0.5.11"
zip = "0.5.13"
serde_json = "1.0.74"
serde = "1.0.133"

rustaria-api = { path = "rustaria-api" }

[build-dependencies]
shaderc = "0.7"

[workspace]
members = ["rustaria-api", "rustaria-core"]

[profile.release]
panic = "abort"
opt-level = "z" # Optimize for size.
lto = true
