[package]
name = "rustaria"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Core
eyre = "0.6.8"
tracing = "0.1.35"
serde = { version = "1.0.137", features = ["derive"] }

# World
hecs = { version = "0.7.6", features = ["serde"] }

# Plugin
zip = "0.6.2"
semver = { version = "1.0.10", features = ["serde"] }
toml = "0.5.9"

# Lua
apollo = { path = "./libs/apollo", features = ["luajit", "vendored", "serialize", "send", "macro"] }

# Networking
laminar = "0.5.0"
bincode = "1.3.3"

# Async
rayon = "1.5.3"
crossbeam = "0.8.1"
parking_lot = "0.12.0"

# Random
rand = "0.8.5"
rand_xoshiro = "0.6.0"

# Math
num = "0.4"
euclid = { version = "0.22.7", features = ["serde"] }

# Util
fxhash = "0.2.1"
bitflags = "1.3.2"
type-map = "0.5"

[workspace]
members = [
    "client",
    "libs/apollo",
    "libs/apollo-macro",
]
