# Rustaria Dedicated Server
# Default Config

[server]

# The socket address the server should listen on.
#
# You should not need to change this, aside from changing the port number to a
# different, unoccupied one for your system.
server_addr = "0.0.0.0:42069"