[package]
name = "rustaria-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustaria = { path = "../" }

mlua = { version = "0.7.1", features = ["luajit", "vendored", "serialize"] }
time = { version = "0.3.5", features = ["macros"] }
futures = "0.3.19"
tokio = { version = "1.15.0", features = ["rt-multi-thread", "macros", "fs"] }
tokio-stream = { version = "0.1.8", features = ["fs"] }
tracing = "0.1.29"
tracing-futures = "0.2.5"
piz = "0.4.0"
memmap = "0.7.0"
eyre = "0.6.5"
color-eyre = "0.6.0"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
structopt = "0.3.25"
